// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4kh3TCsEKNTXKA-TZCTLlDB6rfuUUk3k',
    appId: '1:395239320607:android:682f2a49e114879dfdf92a',
    messagingSenderId: '395239320607',
    projectId: 'seegong-d1d8c',
    storageBucket: 'seegong-d1d8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9FoE6DDr76_cnlf1Rigu6DPZ9UFESu4A',
    appId: '1:395239320607:ios:15daccd22926cc42fdf92a',
    messagingSenderId: '395239320607',
    projectId: 'seegong-d1d8c',
    storageBucket: 'seegong-d1d8c.appspot.com',
    androidClientId: '395239320607-51prhuod0om7ktotoqoqqdh4b42o4sql.apps.googleusercontent.com',
    iosClientId: '395239320607-4tvmv6ljrnpbf9g774fjqlhj9gqsuvom.apps.googleusercontent.com',
    iosBundleId: 'org.tukorea.seegongFlutter',
  );
}
